name: Simple CI

# on.push.branches: main 브랜치에 push(코드 업로드)되면 자동 실행됩니다.
on:
  push:
    branches: ["main"] # main 브랜치에 push가 일어날 때마다 동작

# jobs.build.runs-on: Ubuntu 서버에서 실행(윈도우 PC에서 직접 실행하는 것이 아님).
jobs:
  build:
    runs-on: ubuntu-latest # 깃허브가 자동으로 Ubuntu 서버를 빌려서 실행

    # steps: 자동화로 실행할 작업 목록.
    steps:
      # 첫 번째 step에서 내 소스코드를 서버에 내려받습니다.
      - name: 깃허브 레포지토리 코드 체크아웃
        uses: actions/checkout@v4

      # 두 번째 step에서 index.html 파일이 있는지 확인합니다.
      - name: index.html 파일이 존재하는지 확인
        # 파일이 없으면 실패(exit 1), 있으면 성공 메시지 출력.
        run: |
          if [ -f "index.html" ]; then
            echo "index.html 파일이 있습니다.";
          else
            echo "index.html 파일이 없습니다!";
            exit 1;
          fi
